### ISSUE TITLE
Error when doing /is generator

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/MagicCobblestoneGenerator#54]
#### Describe the bug

Doing `/is generator` shows an internal error and stack trace.

#### Steps to reproduce the behavior

Clean install of addon.
Log in and do `/is generator`

```
[08:22:31 INFO]: BoxManager issued server command: /is generator
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.intopten' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.level' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.level.details.blocks' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.top' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.value' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.create' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.home' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.sethome' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.info' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.lock' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.near' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.expel' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.ban' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.settings' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.language' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.name' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.spawn' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.reset' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.setowner' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.invite' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.reject' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.leave' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.kick' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.accept' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.trust' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.coop' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.island.team.promote' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.settings.*' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: [BentoBox] Player BoxManager has permission: 'bskyblock.stone-generator' <-- the last part MUST be a number! Ignoring...
[08:22:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'is generator' in world.bentobox.bskyblock.BSkyBlock$1(island)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.1.jar:git-Paper-56]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-56]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-56]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1505) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.managers.StoneGeneratorManager.validateIslandData(StoneGeneratorManager.java:551) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.panels.player.GeneratorUserPanel.<init>(GeneratorUserPanel.java:46) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.panels.player.GeneratorUserPanel.openPanel(GeneratorUserPanel.java:68) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.commands.player.GeneratorPlayerCommand.execute(GeneratorPlayerCommand.java:73) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-56]
	... 17 more
> 
```
#### Expected behavior

No error.

##### Output of `/bbox version` (Mandatory)

```
> bbox v
[08:24:17 INFO]: Running PAPER 1.16.1.
[08:24:17 INFO]: BentoBox version: 1.14.0-SNAPSHOT-LOCAL
[08:24:17 INFO]: Database: JSON
[08:24:17 INFO]: Loaded Game Worlds:
[08:24:17 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[08:24:17 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[08:24:17 INFO]: Loaded Addons:
[08:24:17 INFO]: AcidIsland 1.14.0-SNAPSHOT-b821 (ENABLED)
[08:24:17 INFO]: BSkyBlock 1.14.0-SNAPSHOT-b661 (ENABLED)
[08:24:17 INFO]: Level 2.3.0-SNAPSHOT-LOCAL (ENABLED)
[08:24:17 INFO]: MagicCobblestoneGenerator 2.0.0-SNAPSHOT-LOCAL (ENABLED)
>
```

#### Plugins (Optional)

```
[08:24:30 INFO]: Plugins (4): BentoBox, Essentials, PermissionsEx*, PlaceholderAPI

```

**Comment by tastybento** [comment]
I found the bug. Fixing it.
