### ISSUE TITLE
StringIndexOutOfBoundsException on PAPI *_generator_names variables

### ISSUE THREAD

**Issue by FesterHead** [BentoBoxWorld/MagicCobblestoneGenerator#69]
#### Describe the bug
The PAPI *_generator_names variables throw an StringIndexOutOfBoundsException 

#### Steps to reproduce the behavior
1. Enable MagicCobblestone Generator addon 2.0.0+
2. Activate one or more generators
3. Attempt to view the placeholders

```
/papi parse <username> %bskyblock_magiccobblestonegenerator_active_generator_names%
/papi parse <username> %bskyblock_magiccobblestonegenerator_unlocked_generator_names%
/papi parse <username> %bskyblock_magiccobblestonegenerator_purchased_generator_names%
```

See error in console.
```
13.08 17:21:57 [Server] INFO -------- issued server command: /papi parse ----------- %bskyblock_magiccobblestonegenerator_active_generator_names%
13.08 17:21:57 [Server] INFO papi
13.08 17:21:57 [Server] ERROR null
13.08 17:21:57 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.6
13.08 17:21:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[?:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[?:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
13.08 17:21:57 [Server] INFO Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 8
13.08 17:21:57 [Server] INFO at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:824) ~[?:1.8.0_242]
13.08 17:21:57 [Server] INFO at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:253) ~[?:1.8.0_242]
13.08 17:21:57 [Server] INFO at world.bentobox.magiccobblestonegenerator.StoneGeneratorAddon.lambda$registerPlaceholders$7(StoneGeneratorAddon.java:222) ~[?:?]
13.08 17:21:57 [Server] INFO at world.bentobox.bentobox.api.placeholders.placeholderapi.BasicPlaceholderExpansion.onPlaceholderRequest(BasicPlaceholderExpansion.java:47) ~[?:?]
13.08 17:21:57 [Server] INFO at world.bentobox.bentobox.api.placeholders.placeholderapi.AddonPlaceholderExpansion.onPlaceholderRequest(AddonPlaceholderExpansion.java:5) ~[?:?]
13.08 17:21:57 [Server] INFO at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
13.08 17:21:57 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
13.08 17:21:57 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:288) ~[?:?]
13.08 17:21:57 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:261) ~[?:?]
13.08 17:21:57 [Server] INFO at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:217) ~[?:?]
13.08 17:21:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-385]
13.08 17:21:57 [Server] INFO ... 17 more
```

#### Expected behavior
Expect to see a list of active, unlocked, and/or purchased generators.

#### Screenshots and videos (Optional)
n/a

### Environment
n/a

##### Output of `/bbox version` (Mandatory)

```
13.08 17:35:45 [Server] INFO Running PAPER 1.15.2.
13.08 17:35:45 [Server] INFO BentoBox version: 1.14.2
13.08 17:35:45 [Server] INFO Database: JSON
13.08 17:35:45 [Server] INFO Loaded Game Worlds:
13.08 17:35:45 [Server] INFO bskyblock_world (SkyBlock): Overworld, Nether, The End
13.08 17:35:45 [Server] INFO oneblock_world (OneBlock): Overworld
13.08 17:35:45 [Server] INFO Loaded Addons:
13.08 17:35:45 [Server] INFO AOneBlock 1.4.0 (ENABLED)
13.08 17:35:45 [Server] INFO Biomes 1.7.0 (ENABLED)
13.08 17:35:45 [Server] INFO Border 2.0.0-SNAPSHOT-b42 (ENABLED)
13.08 17:35:45 [Server] INFO BSkyBlock 1.13.1 (ENABLED)
13.08 17:35:45 [Server] INFO ExtraMobs 1.11.0.2 (ENABLED)
13.08 17:35:45 [Server] INFO Level 2.4.0 (ENABLED)
13.08 17:35:45 [Server] INFO Limits 1.14.0 (ENABLED)
13.08 17:35:45 [Server] INFO MagicCobblestoneGenerator 2.2.0-SNAPSHOT-b158 (ENABLED)
13.08 17:35:45 [Server] INFO TwerkingForTrees 1.4.1 (ENABLED)
13.08 17:35:45 [Server] INFO Warps 1.9.7 (ENABLED)
```

#### Plugins (Optional)
```
13.08 17:36:38 [Server] INFO Plugins (40): AggressiveAnimals*, Aliases*, AutomaticInventory, AutoTool, BentoBox, BetterBees, BetterFood, BookShelf, BSkyBlockTopTen, CommandPanels, CrazyCrates, EliteMobs, EnchantmentSolution, Essentials, EssentialsSpawn, FastLeafDecay, GiveMeArms, HeadDatabase*, HolographicDisplays, IllegalStack, InfiniteScoreboard, Jobs, LuckPerms, Matrix, MineableSpawners, MobHeads, NBTAPI, PerWorldInventory, PL-Hide, PlaceholderAPI, PlayerGUI, ProtocolLib, Quests, SAML, SmoothSleep, SuperLuckyBlock, TempFly, TimedRestart, uShop, Vault
```
 
### Additional context (Optional)
I believe the error occurs when attempting to delete the last comma from the list.  The code references deleting a character at stringBuilder.length() instead of stringBuilder.length()-1.
```

                    if (stringBuilder.length() > 0)
                    {
                        stringBuilder.deleteCharAt(stringBuilder.length());
                    }
```
In develop branch, these are on lines 220-223, 246-249, 272-275

**Comment by FesterHead** [comment]
I forked the project and tested out a fix.  `_active_generator_names` now works.
<img width="222" alt="2020-08-23_11 45 09" src="https://user-images.githubusercontent.com/1421244/90989560-5416da80-e536-11ea-9022-7a212b9f0fcf.png">

https://github.com/FesterHead/MagicCobblestoneGenerator/commit/343c45eff36f74f7c914fc443acfa65b73cc779d

Not issuing a pull request because `%bskyblock_magiccobblestonegenerator_unlocked_generator_names%` is throwing a new error that I don't know how to fix.  `java.lang.ClassCastException: world.bentobox.magiccobblestonegenerator.database.objects.GeneratorTierObject cannot be cast to java.lang.Comparable`

The `_purchased_generator_names` works and looks to be the same as `_unlocked_generator_names`.

Stack trace.
```
23.08 17:38:00 [Server] INFO --------- issued server command: /papi parse --------- %bskyblock_magiccobblestonegenerator_unlocked_generator_names%
23.08 17:38:00 [Server] INFO papi
23.08 17:38:00 [Server] ERROR null
23.08 17:38:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.10.6
23.08 17:38:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[?:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[?:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
23.08 17:38:00 [Server] INFO Caused by: java.lang.ClassCastException: world.bentobox.magiccobblestonegenerator.database.objects.GeneratorTierObject cannot be cast to java.lang.Comparable
23.08 17:38:00 [Server] INFO at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
23.08 17:38:00 [Server] INFO at world.bentobox.magiccobblestonegenerator.StoneGeneratorAddon.lambda$registerPlaceholders$9(StoneGeneratorAddon.java:243) ~[?:?]
23.08 17:38:00 [Server] INFO at world.bentobox.bentobox.api.placeholders.placeholderapi.BasicPlaceholderExpansion.onPlaceholderRequest(BasicPlaceholderExpansion.java:47) ~[?:?]
23.08 17:38:00 [Server] INFO at world.bentobox.bentobox.api.placeholders.placeholderapi.AddonPlaceholderExpansion.onPlaceholderRequest(AddonPlaceholderExpansion.java:5) ~[?:?]
23.08 17:38:00 [Server] INFO at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
23.08 17:38:00 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
23.08 17:38:00 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:288) ~[?:?]
23.08 17:38:00 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:261) ~[?:?]
23.08 17:38:00 [Server] INFO at me.clip.placeholderapi.commands.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:217) ~[?:?]
23.08 17:38:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-385]
23.08 17:38:00 [Server] INFO ... 17 more
```
