### ISSUE TITLE
IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/MagicCobblestoneGenerator#81]
#### Describe the bug

IllegalArgumentException: bound must be positive error on server console.

#### Steps to reproduce the behavior

Use the generator addon.

#### Expected behavior

No write this error.

##### Output of `/bbox version` (Mandatory)

```
[16:16:50 INFO]: Fut Helytelen (YATOPIA) 1.16.4.
[16:16:50 INFO]: BentoBox verzió: 1.15.3-SNAPSHOT-b1915
[16:16:50 INFO]: Adatbázis: JSON
[16:16:50 INFO]: Betöltött játékvilágok:
[16:16:50 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[16:16:50 INFO]: Betöltött kiegészítők:
[16:16:50 INFO]: AcidIsland 1.14.4 (ENABLED)
[16:16:50 INFO]: Biomes 1.13.0-SNAPSHOT-b196 (ENABLED)
[16:16:50 INFO]: Challenges 0.8.4-SNAPSHOT-b432 (ENABLED)
[16:16:50 INFO]: Chat 1.1.1 (ENABLED)
[16:16:50 INFO]: DimensionalTrees 1.6.1-SNAPSHOT-b82 (ENABLED)
[16:16:50 INFO]: Greenhouses 1.4.1 (ENABLED)
[16:16:50 INFO]: Level 2.5.0-SNAPSHOT-b420 (ENABLED)
[16:16:50 INFO]: Likes 2.1.0-SNAPSHOT-b31 (ENABLED)
[16:16:50 INFO]: MagicCobblestoneGenerator 2.2.0-SNAPSHOT-b194 (ENABLED)
[16:16:50 INFO]: Warps 1.10.1-SNAPSHOT-b268 (ENABLED)
```

#### Plugins (Optional)

```
[16:17:06 INFO]: Plugins (96): AdminVedelem, antiRedstoneClock, AnvilRestrict, ArmorStandEditor, BentoBox, BetterGUI, BungeeHelpop, BuntetesLogolo, ChatControl, ChatReaction, ChestShop, ChestSort, ChristmasCalendar*, Citizens, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CreativeNbtControl, CS-CoreLib, CustomCrafting, Duels, DyedBackpacks, EcoPower, EnderContainers, EntityDetection, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EventekGUI, EventRendszer, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), FluffyMachines, HeadDatabase, HolographicDisplays, HonapStaffja, Jatekido, Kemkedes, Kezdes, LiteXpansion, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NoCheatPlus, OpenInv, PickupSpawners, PlaceholderAPI, PlugMan, PocketGames, PomaBot, PomaDrops, PomaExpansion, PotionArmors, PremiumAds*, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, ShopGUIPlus, Shopkeepers, SkinsRestorer, sleep-most, Slimefun, SlimefunLuckyBlocks, SlimefunPomaFix, StaffChat, StaffTime, SzulinapiKalapok, TAB, TimeIsMoney*, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, Votifier, VotingPlugin, WDLCompanion*, WolfyUtilities, WorldBorder, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags
```
 
### Additional context (Optional)

```
[07:27:45] [Server thread/WARN]: [BentoBox] Task #49864 for BentoBox v1.15.3-SNAPSHOT-b1915 generated an exception
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.tasks.MagicGenerator.processBlockReplacement(MagicGenerator.java:133) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.tasks.MagicGenerator.isCobblestoneReplacementGenerated(MagicGenerator.java:43) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.listeners.GeneratorListener.isCobblestoneReplacementGenerated(GeneratorListener.java:139) ~[?:?]
	at world.bentobox.magiccobblestonegenerator.listeners.VanillaGeneratorListener.lambda$onBlockFormEvent$1(VanillaGeneratorListener.java:91) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1369) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1279) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180) ~[patched_1.16.4.jar:git-Yatopia-"04855bf"]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by BONNe** [comment]
Could you please export your database (`/[admin_command] generator` and click on the Export Database button) and share it?

**Comment by andris155** [comment]
[db.zip](https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/files/5685140/db.zip)

**Comment by andris155** [comment]
Thanks.
